#!/bin/sh
#bismillah
clear

echo ""
echo -e "\033[31m ██████ ██████ ██████ ██████ ██████ ██████ ██     ██████ ██████ \033[0m"
echo -e "\033[31m ██  ██ ██     ██  ██ ██     ██         ██ ██     ██  ██ ██ \033[0m"
echo -e "\033[31m ██████ ████   ██  ██ ████   ██     ██████ ██████ ██  ██ ██ \033[0m"
echo -e "\033[31m     ██ ██     ██  ██ ██     ██     ██  ██ ██     ██  ██ ██ \033[0m"
echo -e "\033[31m ██████ ██████ ██  ██ ██████ ██     ██████ ██████ ██████ ██ \033[0m"
echo "#######################################################"
echo " Author : 7grok "
echo " tool   : http-generator "
echo "#######################################################"
echo ""

echo -n "[*] Masukan Url : "
read a
if [ ! -z $a ]
then
echo "[*] Scanning... "
nmap -p80 --script=http-generator $a
else
echo "[!] Url Belum Di Masukan! "
fi
