#!/bin/sh

clear
echo ""
echo -e "\033[31m ██████ ██ ██     ██████  ██  ██  ██████ ██████ \033[0m"
echo -e "\033[31m ██     ██ ██     ██     ██ ██ ██     ██ ██  ██ \033[0m"
echo -e "\033[31m ██████ ██ ██████ ████   ██    ██ ██████ ██████ \033[0m"
echo -e "\033[31m     ██ ██ ██     ██     ██    ██ ██  ██ ██ \033[0m"
echo -e "\033[31m ██████ ██ ██████ ██████ ██    ██ ██████ ██ \033[0m"
echo "####################################"
echo " Authoe : 7grok "
echo " Tool   : http-sitemap-generator "
echo "####################################"
echo ""

echo -n "[*] Masukan Url : "
read asu
if [ ! -z $asu ]
then
echo "[*] Scanning..."
nmap -p 80 -sV --script=http-sitemap-generator $asu
else
echo "[!] Url Belum Di Masukan! "
fi

