#!/bin/sh

clear

figlet SMB
figlet SYSTEM
figlet INFO
echo ""

echo -n "[*] Masukan Url : "
read a
if [ ! -z $a ]
then
echo "[*] Scanning... "
nmap -p445 --script smb-system-info $a
else
echo "[!] Url Belum Dimasukan! "
fi
