#!/bin/sh

clear

figlet SMB
figlet SECURITY
figlet MODE
echo ""

echo -n "[*] Masukan Url : "
read a
if [ ! -z $a ]
then
echo "[*] Scanning... "
nmap -p445 script smb-security-mode $a
else
echo "[!] Url Belum Dimasukan! "
fi
