#!/bin/sh

clear

figlet  SMB
figlet  ENUM
figlet  PROCESSES
echo ""

echo -n "[*] Masukan Url : "
read b
if [ ! -z $b ]
then
echo "[*] Scanning... "
nmap -p445 --script smb-enum-processes $b
else
echo "[!] Url Belum Dimasukan! "
fi
