#!/bin/sh

clear

figlet SMB-BRUTE
echo ""

echo -n "[*] Masukan Url/Ip : "
read a
if [ ! -z $a ]
then
echo "[*] Looading... "
echo ""
nmap -p 445 --script smb-brute $a -d
else
echo "[!] Url/Ip Belum Dimsukan! "
fi
