#!/bin/sh

clear

figlet  SMB
figlet  ENUM
figlet  SESSIONS
echo ""

echo -n "[*] Masukan Url : "
read p
if [ ! -z $p ]
then
echo "[*] Scanning... "
nmap -p 445 --script smb-enum-sessions $p
else
echo "URL'E RUNG BOK LEBOKNE! "
fi
